use std::fs;
use std::io::{BufRead, BufReader};
use std::net::IpAddr;
use std::path::Path;

use crate::dns_manager::DnsManagerError;

use super::DnsBackend;

const RESOLV_CONF: &str = "/etc/resolv.conf";
const RESOLV_CONF_BACKUP: &str = "/etc/resolv.conf.lightway-orig";
const RESOLV_CONF_TMP: &str = "/etc/resolv.conf.lightway-new";
const GENERATED_MARKER: &str = "Generated by lightway";

/// Direct `/etc/resolv.conf` manipulation backend (legacy fallback).
pub(super) struct DirectFile;

impl DnsBackend for DirectFile {
    fn set(&self, dns_server: IpAddr) -> Result<(), DnsManagerError> {
        backup()?;
        let content = format!("# {GENERATED_MARKER}\nsearch lightway\nnameserver {dns_server}\n");
        write_atomic(&content)
    }

    fn reset(&self) -> Result<(), DnsManagerError> {
        if !generated_by_lightway(RESOLV_CONF) {
            let _ = fs::remove_file(RESOLV_CONF_BACKUP);
            return Ok(());
        }
        match fs::rename(RESOLV_CONF_BACKUP, RESOLV_CONF) {
            Ok(()) => Ok(()),
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => {
                Err(DnsManagerError::NoResolvConfBackup)
            }
            Err(e) => Err(DnsManagerError::FailedToRestoreDnsConfig(e.to_string())),
        }
    }
}

/// Returns `true` if the first line of `path` contains the lightway marker.
fn generated_by_lightway(path: &str) -> bool {
    let file = match fs::File::open(path) {
        Ok(f) => f,
        Err(_) => return false,
    };
    let mut reader = BufReader::new(file);
    let mut first_line = String::new();
    match reader.read_line(&mut first_line) {
        Ok(_) => first_line.contains(GENERATED_MARKER),
        Err(_) => false,
    }
}

fn backup() -> Result<(), DnsManagerError> {
    if !Path::new(RESOLV_CONF).exists() || generated_by_lightway(RESOLV_CONF) {
        return Ok(());
    }
    let _ = fs::remove_file(RESOLV_CONF_BACKUP);
    fs::hard_link(RESOLV_CONF, RESOLV_CONF_BACKUP)
        .map_err(|e| DnsManagerError::FailedToSetDnsConfig(e.to_string()))
}

fn write_atomic(content: &str) -> Result<(), DnsManagerError> {
    fs::write(RESOLV_CONF_TMP, content)
        .map_err(|e| DnsManagerError::FailedToSetDnsConfig(e.to_string()))?;
    fs::rename(RESOLV_CONF_TMP, RESOLV_CONF)
        .map_err(|e| DnsManagerError::FailedToSetDnsConfig(e.to_string()))
}

#[cfg(test)]
mod tests {
    use super::*;
    use serial_test::serial;
    use std::{env, net::Ipv4Addr};
    use test_case::test_case;

    const TEST_IP: IpAddr = IpAddr::V4(Ipv4Addr::new(8, 8, 8, 8));

    #[test]
    #[serial]
    fn test_generated_content_passes_lightway_check() {
        let content = format!("# {GENERATED_MARKER}\nsearch lightway\nnameserver {TEST_IP}\n");
        let temp_path = env::temp_dir().join("test_generated_content");
        fs::write(&temp_path, &content).unwrap();
        assert!(generated_by_lightway(temp_path.to_str().unwrap()));
        let _ = fs::remove_file(&temp_path);
    }

    #[test_case(false, "nameserver 8.8.8.8\nsearch example.com\n" ; "regular resolv conf")]
    #[test_case(false, "" ; "empty file")]
    #[test_case(false, "nameserver 8.8.8.8\n# Generated by lightway\n" ; "marker in wrong position")]
    #[serial]
    fn test_file_detection_with_content(expected: bool, content: &str) {
        let temp_path = env::temp_dir().join("test_file_detection");
        fs::write(&temp_path, content).unwrap();
        assert_eq!(generated_by_lightway(temp_path.to_str().unwrap()), expected);
        let _ = fs::remove_file(&temp_path);
    }

    #[test]
    fn test_missing_file_detection() {
        assert!(!generated_by_lightway("/nonexistent/path"));
    }

    #[test]
    fn test_content_format() {
        let content = format!("# {GENERATED_MARKER}\nsearch lightway\nnameserver {TEST_IP}\n");
        let lines: Vec<&str> = content.lines().collect();
        assert_eq!(lines[0], format!("# {GENERATED_MARKER}"));
        assert_eq!(lines[1], "search lightway");
        assert_eq!(lines[2], "nameserver 8.8.8.8");
    }
}
