[advisories]
version = 2
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
yanked = "deny"
ignore = [
    # yaml_rust is unmaintained, which is a dependency of twelf. Ignoring until its fixed
    "RUSTSEC-2024-0320",
    # instant is unmaintained, which is a dependency of tokio-eventfd. Ignoring until its fixed
    "RUSTSEC-2024-0384",
]

[licenses]
version = 2
allow = [
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "MIT",
    "OpenSSL",
    "Unicode-DFS-2016",
    "WTFPL",
    "Zlib",
]
confidence-threshold = 0.8
exceptions = [
    { name = "wolfssl", allow = ["GPL-2.0"], version = "*" },
    { name = "wolfssl-sys", allow = ["GPL-2.0"], version = "*" },
    { name = "lightway-client", allow = ["GPL-2.0"], version = "*" },
    { name = "lightway-core", allow = ["GPL-2.0"], version = "*" },
    { name = "lightway-server", allow = ["GPL-2.0"], version = "*" },
    { name = "lightway-app-utils", allow = ["GPL-2.0"], version = "*" },
]

[licenses.private]
ignore = true

[bans]
multiple-versions = "deny"
wildcards = "allow"
highlight = "all"
workspace-default-features = "allow"
external-default-features = "allow"
skip = [
    { name = "base64", version = "0.21.7" },
    { name = "block-buffer", version = "0.9.0" },
    { name = "darling", version = "0.14.4" },
    { name = "darling_core", version = "0.14.4" },
    { name = "darling_macro", version = "0.14.4" },
    { name = "digest", version = "0.9.0" },
    { name = "fastrand", version = "1.9.0" },
    { name = "futures-lite", version = "1.13.0" },
    { name = "hashbrown", version = "0.12.3" },
    { name = "heck", version = "0.4.1" },
    { name = "indexmap", version = "1.9.3" },
    { name = "serde_yaml", version = "0.8.26" },
    { name = "strsim", version = "0.10.0" },
    { name = "syn", version = "1.0.109" },
    { name = "thiserror", version = "1.0.69" },
    { name = "thiserror-impl", version = "1.0.69" },
    { name = "windows-sys", version = "0.52.0" },
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = [
    "https://github.com/expressvpn/wolfssl-rs",
]

# See https://github.com/briansmith/ring/blob/main/LICENSE Ring
# contains elements liscensed under all of ISC, MIT and OpenSSL
# licenses.
[[licenses.clarify]]
name = "ring"
expression = "ISC AND MIT AND OpenSSL"
license-files = [{ path = "LICENSE", hash = 0xbd0eed23 }]
