[advisories]
version = 2
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
yanked = "deny"
ignore = [
    # yaml_rust is unmaintained, which is a dependency of twelf. Ignoring until its fixed
    "RUSTSEC-2024-0320",
    # paste is unmaintained, which is a dependency of fs-mistrust->pwd-grp. Ignoring until its fixed
    # https://gitlab.torproject.org/tpo/core/rust-pwd-grp/-/issues/5
    "RUSTSEC-2024-0436",
]

[licenses]
version = 2
allow = [
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "MIT",
    "NCSA",
    "Unicode-3.0",
    "WTFPL",
    "Zlib",
]
confidence-threshold = 0.8
exceptions = [
    { name = "wolfssl", allow = ["GPL-3.0"], version = "*" },
    { name = "wolfssl-sys", allow = ["GPL-3.0"], version = "*" },
    { name = "lightway-client", allow = ["AGPL-3.0"], version = "*" },
    { name = "lightway-core", allow = ["AGPL-3.0"], version = "*" },
    { name = "lightway-server", allow = ["AGPL-3.0"], version = "*" },
    { name = "lightway-app-utils", allow = ["AGPL-3.0"], version = "*" },
]

[licenses.private]
ignore = true

[bans]
multiple-versions = "deny"
wildcards = "allow"
highlight = "all"
workspace-default-features = "allow"
external-default-features = "allow"
skip = [
    { name = "block-buffer", version = "0.9.0" },
    { name = "darling", version = "0.14.4" },
    { name = "darling_core", version = "0.14.4" },
    { name = "darling_macro", version = "0.14.4" },
    { name = "digest", version = "0.9.0" },
    { name = "hashbrown", version = "0.12.3" },
    { name = "heck", version = "0.4.1" },
    { name = "indexmap", version = "1.9.3" },
    { name = "itertools", version = "0.13.0" },
    { name = "serde_yaml", version = "0.8.26" },
    { name = "strsim", version = "0.10.0" },
    { name = "syn", version = "1.0.109" },
    { name = "thiserror", version = "1.0.69" },
    { name = "thiserror-impl", version = "1.0.69" },
    { name = "windows-sys", version = "0.52.0" },
    { name = "windows-sys", version = "0.59.0" },
    { name = "windows-targets", version = "0.52.6" },
    { name = "windows_aarch64_gnullvm", version = "0.52.6" },
    { name = "windows_aarch64_msvc", version = "0.52.6" },
    { name = "windows_i686_gnu", version = "0.52.6" },
    { name = "windows_i686_gnullvm", version = "0.52.6" },
    { name = "windows_i686_msvc", version = "0.52.6" },
    { name = "windows_x86_64_gnu", version = "0.52.6" },
    { name = "windows_x86_64_gnullvm", version = "0.52.6" },
    { name = "windows_x86_64_msvc", version = "0.52.6" },
    { name = "getrandom", version = "0.2.15" },
    { name = "rand", version = "0.8.5" },
    { name = "rand_chacha", version = "0.3.1" },
    { name = "rand_core", version = "0.6.4" },
    { name = "wasi", version = "0.11.0+wasi-snapshot-preview1" }
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = [
    "https://github.com/expressvpn/wolfssl-rs",
]

# See https://github.com/briansmith/ring/blob/main/LICENSE Ring
# contains elements liscensed under all of ISC, MIT and OpenSSL
# licenses.
[[licenses.clarify]]
name = "ring"
expression = "ISC AND MIT AND OpenSSL"
license-files = [{ path = "LICENSE", hash = 0xbd0eed23 }]
