[advisories]
version = 2
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
yanked = "deny"
ignore = [
    # yaml_rust is unmaintained, which is a dependency of twelf. Ignoring until its fixed
    "RUSTSEC-2024-0320",
    # paste is unmaintained, which is a dependency of fs-mistrust->pwd-grp. Ignoring until its fixed
    # https://gitlab.torproject.org/tpo/core/rust-pwd-grp/-/issues/5
    "RUSTSEC-2024-0436",
]

[licenses]
version = 2
allow = [
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "MIT",
    "Unicode-3.0",
    "Zlib",
]
confidence-threshold = 0.8
exceptions = [
    { name = "wolfssl", allow = ["GPL-2.0-or-later"], version = "*" },
    { name = "wolfssl-sys", allow = ["GPL-2.0-or-later"], version = "*" },
    { name = "lightway-client", allow = ["AGPL-3.0-only"], version = "*" },
    { name = "lightway-core", allow = ["AGPL-3.0-only"], version = "*" },
    { name = "lightway-server", allow = ["AGPL-3.0-only"], version = "*" },
    { name = "lightway-app-utils", allow = ["AGPL-3.0-only"], version = "*" },
]

[licenses.private]
ignore = true

[bans]
multiple-versions = "allow"
wildcards = "allow"
highlight = "all"
workspace-default-features = "allow"
external-default-features = "allow"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = [
    # Temporary: wolfssl-rs v5.9.0 upgrade branch (remove once published to crates.io)
    "https://github.com/expressvpn/wolfssl-rs",
]

# See https://github.com/briansmith/ring/blob/main/LICENSE Ring
# contains elements liscensed under all of ISC, MIT and OpenSSL
# licenses.
[[licenses.clarify]]
name = "ring"
expression = "ISC AND MIT AND OpenSSL"
license-files = [{ path = "LICENSE", hash = 0xbd0eed23 }]
