[config]
default_to_workspace = false

[env]
# Platform-specific feature sets
FEATURES_MACOS = "default,debug,postquantum,kyber_only"
FEATURES_LINUX = "default,debug,postquantum,kyber_only,io-uring"

[tasks.clippy]
mac_alias = "clippy-macos"
linux_alias = "clippy-linux"

[tasks.clippy-macos]
description = "Run clippy with macOS features only"
category = "Development"
command = "cargo"
args = ["clippy", "--features", "${FEATURES_MACOS}", "--all-targets", "--", "-D", "warnings"]

[tasks.clippy-linux]
description = "Run clippy with Linux features (including io-uring)"
category = "Development"
command = "cargo"
args = ["clippy", "--features", "${FEATURES_LINUX}", "--all-targets", "--", "-D", "warnings"]