[config]
default_to_workspace = false

[env]
# Platform-specific feature sets
FEATURES_MACOS = "default,debug,postquantum,kyber_only"
FEATURES_LINUX = "default,debug,postquantum,kyber_only,io-uring"

[tasks.clippy]
description = "Run Clippy with platform specific features only"
category = "Development"

[tasks.clippy.mac]
command = "cargo"
args = ["clippy", "--features", "${FEATURES_MACOS}", "--all-targets", "--", "-D", "warnings"]

[tasks.clippy.linux]
command = "cargo"
args = ["clippy", "--features", "${FEATURES_LINUX}", "--all-targets", "--", "-D", "warnings"]