VERSION 0.8
ARG --global debian

build-container:
    ARG TOKIO_WORKER_THREADS
    ARG BACKEND
    ARG EXTRA_FEATURES
    FROM ../base+container --debian=$debian
    IF [ -n "$BACKEND" ]
        COPY (../..+build-backend/lightway-server --BACKEND=$BACKEND --EXTRA_FEATURES=$EXTRA_FEATURES) .
    ELSE
        COPY (../..+build-wolfssl/lightway-server --debian=$debian) .
    END
    COPY --dir --chmod 0660 ../certs+server/* tests/certs/
    COPY --dir --chmod 0660 lwpasswd tests/server/lwpasswd
    COPY --dir docker-entrypoint.sh server_config.yaml token.pub .
    HEALTHCHECK --interval=1s --timeout=1s --start-period=0s --retries=3 CMD [ -n "$(ss -HOlutn sport = :${SERVER_PORT:-443})" ]
    IF [ -n "$TOKIO_WORKER_THREADS" ]
        ENV TOKIO_WORKER_THREADS=$TOKIO_WORKER_THREADS
    END
    ENTRYPOINT ["/docker-entrypoint.sh"]

save-container:
    FROM +build-container --debian=$debian
    SAVE IMAGE lightway-test-server:latest
