use std::{
    net::{IpAddr, Ipv4Addr, SocketAddr},
    path::PathBuf,
};

use anyhow::Context;
use bytesize::ByteSize;
use clap::Parser;
use ipnet::Ipv4Net;
use serde::Deserialize;
use std::time::Duration as StdDuration;
use struct_patch::{Patch, Substrate};

use lightway_app_utils::args::{
    ConnectionType, Duration, IpMap, LogFormat, LogLevel, NonZeroDuration,
};
use lightway_app_utils::{Validate, validate_configuration_file_path};

// NOTE
// The cli argument and options all set to ConfigPatch, which is generated by
// Patch derive, do NOT set defualts in the clap macros, and let all default
// values follow the Rust convention in default trait, such that we are able
// to serialized out any kind of configure from the Config::default()
#[derive(Debug, Deserialize, Patch, Substrate)]
#[patch(attribute(derive(Deserialize, Parser)))]
#[patch(attribute(clap(about = "A lightway server")))]
pub struct Config {
    #[patch(attribute(clap(short, long)))]
    #[patch(attribute(doc = "Config File to load"))]
    pub config_file: PathBuf,

    #[patch(attribute(clap(short, long, value_enum)))]
    #[patch(attribute(doc = "Connection mode"))]
    pub mode: ConnectionType,

    #[patch(attribute(clap(long)))]
    #[patch(attribute(doc = "user database, in Apache htpasswd format"))]
    pub user_db: Option<PathBuf>,

    #[patch(attribute(clap(long)))]
    pub token_rsa_pub_key_pem: Option<PathBuf>,

    #[patch(attribute(clap(long)))]
    #[patch(attribute(doc = "Server certificate"))]
    pub server_cert: PathBuf,

    #[patch(attribute(clap(long)))]
    #[patch(attribute(doc = "Server key"))]
    pub server_key: PathBuf,

    #[patch(attribute(clap(long)))]
    #[patch(attribute(doc = "Tun device name to use"))]
    pub tun_name: Option<String>,

    #[patch(attribute(clap(long)))]
    #[patch(attribute(doc = "IP pool to assign clients"))]
    pub ip_pool: Ipv4Net,

    #[patch(attribute(clap(long)))]
    #[patch(attribute(doc = r#"Additional IP address map.
    Maps from incoming IP address to a subnet of "ip_pool" to use for that address."#))]
    pub ip_map: Option<IpMap>,

    #[patch(attribute(clap(long)))]
    #[patch(attribute(doc = r#"The IP assigned to the Tun device.
    If this is within `ip_pool` then it will be reserved."#))]
    pub tun_ip: Option<Ipv4Addr>,

    #[patch(attribute(clap(long)))]
    #[patch(attribute(doc = "Server IP to send in network_config message"))]
    pub lightway_server_ip: Ipv4Addr,

    #[patch(attribute(clap(long)))]
    #[patch(attribute(doc = "Client IP to send in network_config message"))]
    pub lightway_client_ip: Ipv4Addr,

    #[patch(attribute(clap(long)))]
    #[patch(attribute(doc = "DNS IP to send in network_config message"))]
    pub lightway_dns_ip: Ipv4Addr,

    #[patch(attribute(clap(long)))]
    #[patch(empty_value = false)]
    #[patch(attribute(serde(default)))]
    #[patch(attribute(doc = "Enable Expresslane for [`ConnectionType::Udp`] connections"))]
    pub enable_expresslane: bool,

    #[patch(attribute(clap(long)))]
    #[patch(attribute(doc = "Interval between Expresslane key rotations"))]
    pub expresslane_keys_rotation_interval: Duration,

    #[patch(attribute(clap(long)))]
    #[patch(attribute(doc = "How often to check for aged connections to expire"))]
    pub connection_age_expiration_interval: Duration,

    #[patch(attribute(clap(long)))]
    #[patch(attribute(doc = "Interval between session statistics reports"))]
    pub statistics_reporting_interval: Duration,

    #[patch(attribute(clap(long)))]
    #[patch(empty_value = false)]
    #[patch(attribute(serde(default)))]
    #[patch(attribute(doc = "Enable Post Quantum Crypto"))]
    pub enable_pqc: bool,

    #[patch(attribute(clap(long)))]
    #[patch(empty_value = false)]
    #[patch(attribute(serde(default)))]
    #[patch(attribute(doc = "Enable IO-uring interface for Tunnel"))]
    pub enable_tun_iouring: bool,

    // Any value more than 1024 negatively impact the throughput
    #[patch(attribute(clap(long)))]
    #[patch(attribute(doc = r#"IO-uring submission queue count.
    Only applicable when `enable_tun_iouring` is `true`"#))]
    pub iouring_entry_count: usize,

    #[patch(attribute(clap(long)))]
    #[patch(attribute(doc = r#"IO-uring sqpoll idle time.
    If non-zero use a kernel thread to perform submission queue polling.
    After the given idle time the thread will go to sleep."#))]
    pub iouring_sqpoll_idle_time: Duration,

    #[patch(attribute(clap(long, value_enum)))]
    #[patch(attribute(doc = "Log format"))]
    pub log_format: LogFormat,

    #[patch(attribute(clap(long, value_enum)))]
    #[patch(attribute(doc = "Log level to use"))]
    pub log_level: LogLevel,

    #[patch(attribute(clap(long)))]
    #[patch(attribute(doc = "The key update interval for DTLS/TLS 1.3 connections"))]
    pub key_update_interval: NonZeroDuration,

    #[patch(attribute(clap(long)))]
    #[patch(attribute(doc = "Address to listen to"))]
    pub bind_address: SocketAddr,

    #[patch(attribute(clap(long)))]
    #[patch(empty_value = false)]
    #[patch(attribute(serde(default)))]
    #[patch(attribute(doc = "Enable PROXY protocol support (TCP only)"))]
    pub proxy_protocol: bool,

    #[patch(attribute(clap(long)))]
    #[patch(attribute(doc = "Set UDP buffer size. Default value is 15 MiB."))]
    pub udp_buffer_size: ByteSize,

    #[patch(attribute(clap(long)))]
    #[patch(empty_value = false)]
    #[patch(attribute(serde(default)))]
    #[patch(attribute(doc = "Enable batch receive (`recvmsg_x` on macOS, `recvmmsg` on Linux)"))]
    pub enable_batch_receive: bool,

    #[cfg(feature = "debug")]
    #[patch(attribute(clap(long)))]
    #[patch(empty_value = false)]
    #[patch(attribute(serde(default)))]
    #[patch(attribute(doc = "Enable TLS debug logging"))]
    pub tls_debug: bool,

    #[cfg(feature = "debug")]
    #[patch(attribute(clap(long)))]
    #[patch(empty_value = false)]
    #[patch(attribute(serde(default)))]
    #[patch(attribute(doc = r#"Disable IP pool randomization
    Should be used for debugging only"#))]
    pub randomize_ippool: bool,
}

impl Default for Config {
    fn default() -> Config {
        const IP_POOL: Ipv4Net = match Ipv4Net::new(Ipv4Addr::new(10, 125, 0, 0), 16) {
            Ok(v) => v,
            Err(_) => panic!("Invalid ip pool default constant!"),
        };

        Config {
            config_file: PathBuf::default(),
            mode: ConnectionType::Tcp,
            user_db: None,
            token_rsa_pub_key_pem: None,
            server_cert: PathBuf::from("./server.crt"),
            server_key: PathBuf::from("./server.key"),
            tun_name: None,
            ip_pool: IP_POOL,
            ip_map: None,
            tun_ip: None,
            lightway_server_ip: Ipv4Addr::new(10, 125, 0, 6),
            lightway_client_ip: Ipv4Addr::new(10, 125, 0, 5),
            lightway_dns_ip: Ipv4Addr::new(10, 125, 0, 1),
            enable_expresslane: false,
            expresslane_keys_rotation_interval: Duration::from_std_duration(
                crate::DEFAULT_EXPRESSLANE_KEYS_ROTATION_INTERVAL,
            ),
            connection_age_expiration_interval: Duration::from_std_duration(
                crate::DEFAULT_CONNECTION_AGE_EXPIRATION_INTERVAL,
            ),
            statistics_reporting_interval: Duration::from_std_duration(
                crate::DEFAULT_STATISTICS_REPORTING_INTERVAL,
            ),
            enable_pqc: false,
            enable_tun_iouring: false,
            iouring_entry_count: 1024,
            iouring_sqpoll_idle_time: Duration::from_std_duration(StdDuration::from_millis(100)),
            log_format: LogFormat::Full,
            log_level: LogLevel::Info,
            // TODO: use from_mins, if MSRV > 1.91
            key_update_interval: NonZeroDuration::from_std_duration(StdDuration::from_secs(
                15 * 60,
            )),
            bind_address: SocketAddr::new(IpAddr::V4(Ipv4Addr::new(0, 0, 0, 0)), 27690),
            proxy_protocol: false,
            udp_buffer_size: ByteSize::mib(15),
            enable_batch_receive: false,
            #[cfg(feature = "debug")]
            tls_debug: false,
            #[cfg(feature = "debug")]
            randomize_ippool: true,
        }
    }
}

impl Config {
    /// Allow downstream to skip validation on some fields
    pub fn validate_without(&self, skips: &[&'static str]) -> anyhow::Result<()> {
        if !skips.contains(&"server_key") {
            validate_configuration_file_path(&self.server_key, Validate::OwnerOnly).with_context(
                || format!("Invalid server key file {}", self.server_key.display()),
            )?;
        }

        if !skips.contains(&"server_cert") {
            validate_configuration_file_path(&self.server_cert, Validate::AllowWorldRead)
                .with_context(|| {
                    format!("Invalid server cert file {}", self.server_cert.display())
                })?;
        }

        if !skips.contains(&"user_db")
            && let Some(user_db) = &self.user_db
        {
            validate_configuration_file_path(user_db, Validate::OwnerOnly)
                .with_context(|| format!("Invalid user db file {}", user_db.display()))?;
        }

        if self.enable_expresslane && !skips.contains(&"enable_expresslane") {
            anyhow::ensure!(self.mode.is_udp(), "Expresslane only work in udp mode")
        }

        if self.proxy_protocol && !skips.contains(&"proxy_protocol") {
            anyhow::ensure!(
                self.mode.is_tcp(),
                "Proxy protocol only support with tcp mode"
            )
        }

        Ok(())
    }

    /// validate without any skip
    pub fn validate(&self) -> anyhow::Result<()> {
        self.validate_without(&[])
    }
}

// Note it easier to see what is different from default in each testcase
#[allow(clippy::field_reassign_with_default)]
#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn validate_default_config_without_files() {
        let config = Config::default();
        assert!(
            config
                .validate_without(&["server_key", "server_cert", "user_db"])
                .is_ok()
        );
    }

    #[test]
    fn validate_enable_expresslane() {
        let mut config = Config::default();
        config.mode = ConnectionType::Tcp;
        config.enable_expresslane = true;
        assert!(
            config
                .validate_without(&["server_key", "server_cert", "user_db"])
                .is_err()
        );
    }

    #[test]
    fn validate_proxy_protocol() {
        let mut config = Config::default();
        config.mode = ConnectionType::Udp;
        config.proxy_protocol = true;
        assert!(
            config
                .validate_without(&["server_key", "server_cert", "user_db"])
                .is_err()
        );
    }
}
