[package]
name = "lightway-boring"
version = "0.1.0"
edition.workspace = true
description = "BoringSSL-backed TLS/DTLS abstraction layer for Lightway"
repository.workspace = true
license = "Apache-2.0"

[features]
debug = []

[dependencies]
boring = "5.2.0"
boring-sys = "5.2.0"
bytes = { workspace = true }
foreign-types = "0.5"
libc = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
zeroize = "1.9.0"

[dev-dependencies]
rcgen = { workspace = true }
