use crate::dns_manager::{DnsManagerError, DnsSetup};
use std::env;
use std::fs;
use std::io::{BufRead, BufReader};
use std::path::Path;

const RESOLV_CONF: &str = "/etc/resolv.conf";
const RESOLV_CONF_BACKUP: &str = "/etc/resolv.conf.lightway-orig";
const RESOLV_CONF_TMP: &str = "/etc/resolv.conf.lightway-new";
const GENERATED_MARKER: &str = "Generated by lightway";
const LEGACY_RESOLV_CONF: &str = "/var/lib/expressvpn/resolv.conf";
const LEGACY_RESOLV_CONF_BACKUP: &str = "/var/lib/expressvpn/resolv.conf.orig";

#[derive(Default)]
pub struct DnsManager {
    setup: bool,
}

impl DnsManager {
    /// Checks if a resolv.conf file was generated by lightway by looking for the marker comment
    fn generated_by_lightway(path: &str) -> bool {
        let file = match fs::File::open(path) {
            Ok(file) => file,
            Err(_) => return false,
        };

        let mut reader = BufReader::new(file);
        let mut first_line = String::new();
        match reader.read_line(&mut first_line) {
            Ok(_) => first_line.contains(GENERATED_MARKER),
            Err(_) => false,
        }
    }

    /// Creates a hard link backup of the existing resolv.conf if it exists and wasn't generated by lightway
    /// Since the temporary location is in the same directory a hardlink is always possible
    ///
    /// This is undone by [`DnsManager::restore_previous_config`]
    fn backup_existing_config(&self) -> Result<(), DnsManagerError> {
        if !Path::new(RESOLV_CONF).exists() {
            return Ok(());
        }

        if Self::generated_by_lightway(RESOLV_CONF) {
            return Ok(());
        }

        // Remove existing backup if present
        let _ = fs::remove_file(RESOLV_CONF_BACKUP);

        // Create hard link backup
        fs::hard_link(RESOLV_CONF, RESOLV_CONF_BACKUP)
            .map_err(|e| DnsManagerError::FailedToSetDnsConfig(e.to_string()))?;

        Ok(())
    }

    /// Generates resolv.conf content using provided DNS server as primary, with environment variables as fallback
    ///
    /// Example environment variables from OpenVPN/Lightway:
    /// - foreign_option_1='dhcp-option DNS 193.43.27.132'
    /// - foreign_option_2='dhcp-option DNS 193.43.27.133'  
    /// - foreign_option_3='dhcp-option DOMAIN be.bnc.ch'
    fn generate_resolv_conf_content(dns_server: &str) -> String {
        let mut searches = vec!["lightway".to_string()];
        let mut nameservers = Vec::new();

        if !dns_server.is_empty() {
            nameservers.push(dns_server.to_string());
        }

        for (key, value) in env::vars() {
            if !key.starts_with("foreign_option_") {
                continue;
            }

            let parts: Vec<&str> = value.split_whitespace().collect();
            if parts.len() < 3 || parts[0] != "dhcp-option" {
                continue;
            }

            match parts[1] {
                "DNS" => {
                    if parts[2] != dns_server {
                        nameservers.push(parts[2].to_string());
                    }
                }
                "DOMAIN" => searches.push(parts[2].to_string()),
                _ => continue,
            }
        }

        let mut content = format!("# {}\n", GENERATED_MARKER);

        if !searches.is_empty() {
            content.push_str(&format!("search {}\n", searches.join(" ")));
        }

        for ns in nameservers {
            content.push_str(&format!("nameserver {}\n", ns));
        }

        content
    }

    /// Writes the DNS configuration to resolv.conf atomically using a temporary file
    ///
    /// Cleans up any stale file at a path used by older version of xv_engine to
    /// store the resolve.conf (which was then symlinked to /etc/resolv/conf) since
    /// at this point it cannot possibly be in use any more
    fn apply_configuration(&self, content: &str) -> Result<(), DnsManagerError> {
        fs::write(RESOLV_CONF_TMP, content)
            .map_err(|e| DnsManagerError::FailedToSetDnsConfig(e.to_string()))?;

        fs::rename(RESOLV_CONF_TMP, RESOLV_CONF)
            .map_err(|e| DnsManagerError::FailedToSetDnsConfig(e.to_string()))?;

        let _ = fs::remove_file(LEGACY_RESOLV_CONF);

        Ok(())
    }

    /// Restores the original resolv.conf from backup if the current one was generated by lightway
    fn restore_previous_config(&self) -> Result<(), DnsManagerError> {
        if !Self::generated_by_lightway(RESOLV_CONF) {
            let _ = fs::remove_file(RESOLV_CONF_BACKUP);
            let _ = fs::remove_file(LEGACY_RESOLV_CONF_BACKUP);
            return Ok(());
        }

        match fs::rename(RESOLV_CONF_BACKUP, RESOLV_CONF) {
            Ok(()) => {
                let _ = fs::remove_file(LEGACY_RESOLV_CONF_BACKUP);
                Ok(())
            }
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => {
                match fs::rename(LEGACY_RESOLV_CONF_BACKUP, RESOLV_CONF) {
                    Ok(()) => Ok(()),
                    Err(f) if f.kind() == std::io::ErrorKind::NotFound => {
                        Err(DnsManagerError::NoResolvConfBackup)
                    }
                    Err(f) => Err(DnsManagerError::FailedToRestoreDnsConfig(f.to_string())),
                }
            }
            Err(e) => Err(DnsManagerError::FailedToRestoreDnsConfig(e.to_string())),
        }
    }
}

impl DnsSetup for DnsManager {
    fn set_dns(&mut self, dns_server: &str) -> Result<(), DnsManagerError> {
        if self.setup {
            return Err(DnsManagerError::DnsAlreadyConfigured);
        }
        self.backup_existing_config()?;

        let content = Self::generate_resolv_conf_content(dns_server);

        self.apply_configuration(&content)?;

        self.setup = true;
        Ok(())
    }

    fn reset_dns(&mut self) -> Result<(), DnsManagerError> {
        self.restore_previous_config()?;
        self.setup = false;
        Ok(())
    }
}

impl Drop for DnsManager {
    fn drop(&mut self) {
        if self.setup
            && let Err(e) = self.reset_dns()
        {
            tracing::warn!("Failed to reset DNS configuration during cleanup: {:?}", e);
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use serial_test::serial;
    use std::env;
    use test_case::test_case;

    #[test_case("8.8.8.8" ; "with ip address")]
    #[test_case("dns.google" ; "with hostname")]
    #[test_case("" ; "empty dns server")]
    #[serial]
    fn test_generated_content_passes_lightway_check(dns_server: &str) {
        let content = DnsManager::generate_resolv_conf_content(dns_server);

        test_file_detection_with_content(true, &content);
    }

    #[test_case(false, "nameserver 8.8.8.8\nsearch example.com\n" ; "regular resolv conf")]
    #[test_case(false, "" ; "empty file")]
    #[test_case(false, "nameserver 8.8.8.8\n# Generated by lightway\n" ; "marker in wrong position")]
    #[serial]
    fn test_file_detection_with_content(expected: bool, content: &str) {
        let temp_path = env::temp_dir().join("test_file_detection");
        fs::write(&temp_path, content).unwrap();

        assert_eq!(
            DnsManager::generated_by_lightway(temp_path.to_str().unwrap()),
            expected
        );

        let _ = fs::remove_file(&temp_path);
    }

    #[test]
    fn test_missing_file_detection() {
        assert!(!DnsManager::generated_by_lightway("/nonexistent/path"));
    }

    #[test]
    fn test_content_format() {
        let content = DnsManager::generate_resolv_conf_content("8.8.8.8");
        let lines: Vec<&str> = content.lines().collect();

        assert_eq!(lines[0], format!("# {GENERATED_MARKER}"));
        assert_eq!(lines[1], "search lightway");
        assert_eq!(lines[2], "nameserver 8.8.8.8");
    }

    #[test]
    fn test_dns_already_configured_error() {
        let mut dns_manager = DnsManager { setup: true };
        let result = dns_manager.set_dns("8.8.8.8");

        assert!(matches!(result, Err(DnsManagerError::DnsAlreadyConfigured)));
    }
}
