#[cfg(desktop)]
use super::dns_manager::DnsConfigMode;
#[cfg(desktop)]
use super::route_manager::RouteMode;
use anyhow::{Result, anyhow};
use bytesize::ByteSize;
use clap::Parser;
#[cfg(feature = "postquantum")]
use lightway_app_utils::args::KeyShare;
use lightway_app_utils::args::{Cipher, ConnectionType, Duration, LogLevel, NonZeroDuration};
use lightway_core::{AuthMethod, MAX_OUTSIDE_MTU};
use serde::Deserialize;
use std::time::Duration as StdDuration;
use std::{net::Ipv4Addr, path::PathBuf};
use struct_patch::Patch;

// NOTE
// The cli argument and options all set to ConfigPatch, which is generated by
// Patch derive, do NOT set defualts in the clap macros, and let all default
// values follow the Rust convention in Default trait, such that we are able
// to serialized out any kind of configure from the Config::default(), such
// that our library will be nice and easy to further do integrations.
#[derive(Debug, Deserialize, Patch)]
#[patch(attribute(derive(Deserialize, Parser)))]
#[patch(attribute(command(about = "A lightway client")))]
pub struct Config {
    #[patch(attribute(clap(short, long)))]
    #[patch(attribute(doc = "Config File to load"))]
    pub config_file: PathBuf,

    /// Servers to attempt to connect to. Configuration is only supported in
    /// config file, not command line or environment variable
    #[patch(attribute(clap(skip)))]
    #[serde(default)]
    pub servers: Vec<ConnectionConfig>,

    #[patch(attribute(clap(short, long)))]
    #[patch(attribute(doc = r#"Server to connect to in `<hostname>:<port>` format
    Only used if `servers` is empty"#))]
    pub server: String,

    #[patch(attribute(clap(short, long)))]
    #[patch(attribute(doc = r#"Connection mode
    Only used if `servers` is empty"#))]
    pub mode: ConnectionType,

    #[patch(attribute(clap(long)))]
    #[patch(attribute(doc = r#"Server domain name
    Only used if `servers` is empty"#))]
    pub server_dn: Option<String>,

    #[patch(attribute(clap(long, value_enum)))]
    #[patch(attribute(doc = r#"Cipher to use for encryption
    Only used if `servers` is empty"#))]
    pub cipher: Cipher,

    #[patch(attribute(clap(long, hide = true)))]
    #[patch(attribute(doc = r#"Auth token
    If both token and user/pass are provided, token auth will
    be used. user/pass will be ignored in this case"#))]
    pub token: Option<String>,

    #[patch(attribute(clap(short, long, hide = true)))]
    #[patch(attribute(doc = "Username for auth"))]
    pub user: Option<String>,

    #[patch(attribute(clap(short, long, hide = true)))]
    #[patch(attribute(doc = "Password for auth"))]
    pub password: Option<String>,

    #[patch(attribute(clap(long)))]
    #[patch(attribute(doc = r#"CA certificate
    This can either be a path to the file, or a string starting with
    "-----BEGIN CERTIFICATE-----""#))]
    pub ca_cert: String,

    #[patch(attribute(clap(long)))]
    #[patch(attribute(doc = "Outside (wire) MTU"))]
    pub outside_mtu: usize,

    #[patch(attribute(clap(short, long)))]
    #[patch(attribute(doc = "Tun device name to use"))]
    pub tun_name: Option<String>,

    #[cfg(windows)]
    #[patch(attribute(clap(long)))]
    #[patch(attribute(doc = "Path to wintun.dll file (Windows only)"))]
    pub wintun_file: Option<String>,

    #[cfg(windows)]
    #[patch(attribute(clap(long)))]
    #[patch(attribute(doc = r#"
    Fixed GUID for the Wintun adapter (Windows only).
    Ensures adapter creation retries reuse the same device node.
    Accepts a UUID string (e.g. "550e8400-e29b-41d4-a716-446655440000")."#))]
    pub device_guid: Option<String>,

    #[patch(attribute(clap(long)))]
    #[patch(attribute(doc = "Local IP to use in Tun device"))]
    pub tun_local_ip: Ipv4Addr,

    #[patch(attribute(clap(long)))]
    #[patch(attribute(doc = "Peer IP to use in Tun device"))]
    pub tun_peer_ip: Ipv4Addr,

    #[patch(attribute(clap(long)))]
    #[patch(attribute(doc = "DNS IP to use in Tun device"))]
    pub tun_dns_ip: Ipv4Addr,

    #[cfg(feature = "postquantum")]
    #[patch(attribute(clap(long, value_enum)))]
    pub keyshare: KeyShare,

    #[patch(attribute(clap(long)))]
    #[patch(attribute(doc = "Interval between keepalives"))]
    pub keepalive_interval: NonZeroDuration,

    #[patch(attribute(clap(long)))]
    #[patch(attribute(doc = "Keepalive timeout"))]
    pub keepalive_timeout: NonZeroDuration,

    #[patch(attribute(clap(long)))]
    #[patch(empty_value = false)]
    #[patch(attribute(serde(default)))]
    #[patch(attribute(doc = "Enable continuous Keepalive"))]
    pub keepalive_continuous: bool,

    #[patch(attribute(clap(long)))]
    #[patch(attribute(doc = r#"Time it takes to trigger a tracer packet
    when we haven't received an outside packet"#))]
    pub tracer_packet_timeout: NonZeroDuration,

    #[patch(attribute(clap(long)))]
    #[patch(
        attribute(doc = r#"How long to wait before selecting the best connection.
    If the preferred connection connects before the timeout, it will be used immediately."#)
    )]
    pub preferred_connection_wait_interval: Duration,

    #[patch(attribute(clap(long)))]
    #[patch(attribute(doc = "Socket send buffer size"))]
    pub sndbuf: ByteSize,

    #[patch(attribute(clap(long)))]
    #[patch(attribute(doc = "Socket receive buffer size"))]
    pub rcvbuf: ByteSize,

    #[cfg(batch_receive)]
    #[patch(attribute(clap(long)))]
    #[patch(empty_value = false)]
    #[patch(attribute(serde(default)))]
    #[patch(attribute(
        doc = "Enable batch receive (`recvmsg_x` on macOS, `recvmmsg` on Linux/Android))"
    ))]
    pub enable_batch_receive: bool,

    #[cfg(desktop)]
    #[patch(attribute(clap(long, value_enum)))]
    #[patch(attribute(doc = r#"Setup of route table
    Modes:
        default: Sets up routes as specified in server, tun_local_ip, tun_peer_ip, tun_dns_ip
        noexec : Does not setup any routes
        lan    : Sets up default + additional lan routes"#))]
    pub route_mode: RouteMode,

    #[cfg(desktop)]
    #[patch(attribute(clap(long, value_enum)))]
    #[patch(attribute(doc = r#"DNS configuration mode
    Modes:
        default: Sets up DNS Configuration based on target platform
        noexec : Skips DNS Configuration setup"#))]
    pub dns_config_mode: DnsConfigMode,

    #[patch(attribute(clap(long, value_enum)))]
    #[patch(attribute(doc = "Log level to use"))]
    pub log_level: LogLevel,

    #[patch(attribute(clap(long)))]
    #[patch(empty_value = false)]
    #[patch(attribute(serde(default)))]
    #[patch(attribute(doc = "Enable Expresslane for [`ConnectionType::Udp`] connections"))]
    pub enable_expresslane: bool,

    #[patch(attribute(clap(long)))]
    #[patch(empty_value = false)]
    #[patch(attribute(serde(default)))]
    #[patch(attribute(doc = "Enable PMTU discovery for [`ConnectionType::Udp`] connections"))]
    pub enable_pmtud: bool,

    #[patch(attribute(clap(long)))]
    #[patch(attribute(doc = "Base MTU to use for PMTU discovery"))]
    pub pmtud_base_mtu: Option<u16>,

    #[patch(attribute(clap(long)))]
    #[patch(empty_value = false)]
    #[patch(attribute(serde(default)))]
    #[patch(attribute(doc = "Enable IO-uring interface for Tunnel"))]
    pub enable_tun_iouring: bool,

    // Any value more than 1024 negatively impact the throughput
    #[patch(attribute(clap(long)))]
    #[patch(attribute(doc = r#"IO-uring submission queue count.
    Only applicable when `enable_tun_iouring` is `true`"#))]
    pub iouring_entry_count: usize,

    #[patch(attribute(clap(long)))]
    #[patch(attribute(doc = r#"IO-uring sqpoll idle time.
    If non-zero use a kernel thread to perform submission queue polling.
    After the given idle time the thread will go to sleep."#))]
    pub iouring_sqpoll_idle_time: Duration,

    #[patch(attribute(clap(short, long)))]
    #[patch(empty_value = false)]
    #[patch(attribute(serde(default)))]
    #[patch(
        attribute(doc = r#"Enable inside packet encoding once lightway connects
    Only used if a codec is set"#)
    )]
    pub enable_inside_pkt_encoding_at_connect: bool,

    #[cfg(feature = "debug")]
    #[patch(attribute(clap(long)))]
    #[patch(attribute(doc = "File path to save wireshark keylog"))]
    pub keylog: Option<PathBuf>,

    #[cfg(feature = "debug")]
    #[patch(attribute(clap(long)))]
    #[patch(empty_value = false)]
    #[patch(attribute(serde(default)))]
    #[patch(attribute(doc = "Enable WolfSSL debug logging"))]
    pub tls_debug: bool,

    #[cfg(windows)]
    #[patch(attribute(clap(long)))]
    #[patch(
        attribute(doc = r#"Wintun ring buffer capacity in bytes (Windows only).
    Must be a power of two between 128KiB and 64MiB.
    Larger values improve throughput."#)
    )]
    pub wintun_ring_capacity: ByteSize,

    #[cfg(windows)]
    #[patch(attribute(clap(long)))]
    #[patch(empty_value = false)]
    #[patch(attribute(serde(default)))]
    #[patch(attribute(doc = r#"Enable DPAPI encryption/decryption for config file
    Only for Windows platform"#))]
    pub enable_dpapi: bool,
}

impl Config {
    pub fn take_auth(&mut self) -> Result<AuthMethod> {
        match (self.token.take(), self.user.take(), self.password.take()) {
            (Some(token), _, _) => Ok(AuthMethod::Token { token }),
            (_, Some(user), Some(password)) => Ok(AuthMethod::UserPass { user, password }),
            _ => Err(anyhow!(
                "Either a token or username and password is required"
            )),
        }
    }
}

impl Default for Config {
    fn default() -> Config {
        Config {
            config_file: PathBuf::default(),
            servers: Vec::default(),
            server: String::default(),
            mode: ConnectionType::Tcp,
            server_dn: None,
            cipher: Cipher::Aes256,
            token: None,
            user: None,
            password: None,
            ca_cert: "./ca_cert.crt".to_string(),
            outside_mtu: MAX_OUTSIDE_MTU,
            #[cfg(macos)]
            tun_name: None,
            #[cfg(not(macos))]
            tun_name: Some("lightway".to_string()),
            #[cfg(windows)]
            wintun_file: None,
            #[cfg(windows)]
            device_guid: None,
            tun_local_ip: Ipv4Addr::new(100, 64, 0, 6),
            tun_peer_ip: Ipv4Addr::new(100, 64, 0, 5),
            tun_dns_ip: Ipv4Addr::new(100, 64, 0, 1),
            #[cfg(feature = "postquantum")]
            keyshare: KeyShare::default(),
            keepalive_interval: NonZeroDuration::from_std_duration(StdDuration::from_secs(10)),
            keepalive_timeout: NonZeroDuration::from_std_duration(StdDuration::from_secs(60)),
            keepalive_continuous: true,
            tracer_packet_timeout: NonZeroDuration::from_std_duration(StdDuration::from_secs(10)),
            preferred_connection_wait_interval: Duration::from_std_duration(
                StdDuration::from_secs(0),
            ),
            sndbuf: ByteSize::mib(8),
            rcvbuf: ByteSize::mib(8),
            #[cfg(batch_receive)]
            enable_batch_receive: false,
            #[cfg(desktop)]
            route_mode: RouteMode::default(),
            #[cfg(desktop)]
            dns_config_mode: DnsConfigMode::default(),
            log_level: LogLevel::Info,
            enable_expresslane: false,
            enable_pmtud: false,
            pmtud_base_mtu: None,
            enable_tun_iouring: false,
            iouring_entry_count: 1024,
            iouring_sqpoll_idle_time: Duration::from_std_duration(StdDuration::from_millis(100)),
            enable_inside_pkt_encoding_at_connect: false,
            #[cfg(feature = "debug")]
            keylog: None,
            #[cfg(feature = "debug")]
            tls_debug: false,
            #[cfg(windows)]
            wintun_ring_capacity: ByteSize::mib(8),
            #[cfg(windows)]
            enable_dpapi: false,
        }
    }
}

#[derive(Parser, Debug, Deserialize, PartialEq)]
pub struct ConnectionConfig {
    /// Server to connect to in `<hostname>:<port>` format
    pub server: String,

    /// Connection mode
    #[serde(default)]
    pub mode: ConnectionType,

    /// Server domain name
    #[serde(default)]
    pub server_dn: Option<String>,

    /// Cipher to use for encryption
    #[serde(default)]
    pub cipher: Cipher,
}

#[cfg(test)]
mod tests {
    use std::fs::read_to_string;
    use std::str::FromStr;

    use super::*;
    use test_case::test_case;

    #[test_case("../tests/client/client_config.yaml", true, 0)]
    #[test_case(
        "../tests/client/parallel_connect/client_config.tcp_then_udp.yaml",
        false,
        2
    )]
    #[test_case("../tests/client/parallel_connect/client_config.tcp.yaml", false, 10)]
    #[test_case(
        "../tests/client/parallel_connect/client_config.udp_then_tcp.yaml",
        false,
        2
    )]
    #[test_case("../tests/client/parallel_connect/client_config.udp.yaml", false, 10)]
    fn test_parse_config(config_file: &str, has_top_level_server: bool, servers_len: usize) {
        let matches =
            ConfigPatch::try_parse_from(["lightway-client", "--config-file", config_file]);
        let mut config = Config::default();
        let config_file = PathBuf::from_str(config_file).unwrap();
        let yaml_patch =
            serde_saphyr::from_str::<ConfigPatch>(&read_to_string(config_file).unwrap()).unwrap();
        config.apply(yaml_patch);
        config.apply(matches.unwrap());

        assert_eq!(config.server.is_empty(), !has_top_level_server);
        assert_eq!(config.servers.len(), servers_len);
    }
}
