#[cfg(desktop)]
use super::dns_manager::DnsConfigMode;
#[cfg(desktop)]
use super::route_manager::RouteMode;
use bytesize::ByteSize;
use clap::Parser;
#[cfg(feature = "postquantum")]
use lightway_app_utils::args::KeyShare;
use lightway_app_utils::args::{
    Cipher, ConfigFormat, ConnectionType, Duration, LogLevel, NonZeroDuration,
};
use lightway_core::{AuthMethod, MAX_OUTSIDE_MTU, RootCertificate};
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};
use std::time::Duration as StdDuration;
use std::{net::Ipv4Addr, path::PathBuf};
use struct_patch::Patch;

#[cfg(feature = "mobile")]
use std::net::IpAddr;

// NOTE
// The cli argument and options all set to ConfigPatch, which is generated by
// Patch derive, do NOT set defualts in the clap macros, and let all default
// values follow the Rust convention in Default trait, such that we are able
// to serialized out any kind of configure from the Config::default(), such
// that our library will be nice and easy to further do integrations.
#[derive(Clone, Debug, PartialEq, Deserialize, JsonSchema, Serialize, Patch)]
#[patch(attribute(derive(Clone, Deserialize, Parser)))]
#[patch(attribute(command(about = "A lightway client")))]
pub struct Config {
    #[patch(attribute(clap(short, long)))]
    #[patch(attribute(
        doc = "Generate configure for single server in the format to path from `-c, --config-file`"
    ))]
    #[serde(skip_serializing)]
    pub generate: ConfigFormat,

    #[patch(attribute(clap(short, long)))]
    #[patch(attribute(doc = "Config File to load"))]
    #[serde(skip_serializing)]
    pub config_file: PathBuf,

    /// Servers to attempt to connect to. Configuration is only supported in
    /// config file, not command line or environment variable
    #[patch(attribute(clap(skip)))]
    #[serde(default)]
    #[serde(skip_serializing)]
    pub servers: Vec<ConnectionConfig>,

    #[patch(attribute(clap(short, long)))]
    #[patch(attribute(doc = r#"Server to connect to in `<hostname>:<port>` format
    Only used if `servers` is empty"#))]
    pub server: String,

    #[patch(attribute(clap(short, long)))]
    #[patch(attribute(doc = r#"Connection mode
    Only used if `servers` is empty"#))]
    pub mode: ConnectionType,

    #[patch(attribute(clap(long)))]
    #[patch(attribute(doc = r#"Server domain name
    Only used if `servers` is empty"#))]
    pub server_dn: Option<String>,

    #[patch(attribute(clap(long, value_enum)))]
    #[patch(attribute(doc = r#"Cipher to use for encryption
    Only used if `servers` is empty"#))]
    pub cipher: Cipher,

    #[patch(attribute(clap(long, hide = true)))]
    #[patch(attribute(doc = r#"Auth token
    If both token and user/pass are provided, token auth will
    be used. user/pass will be ignored in this case"#))]
    pub token: Option<String>,

    #[patch(attribute(clap(short, long, hide = true)))]
    #[patch(attribute(doc = "Username for auth"))]
    pub user: Option<String>,

    #[patch(attribute(clap(short, long, hide = true)))]
    #[patch(attribute(doc = "Password for auth"))]
    pub password: Option<String>,

    #[patch(attribute(clap(long)))]
    #[patch(attribute(doc = r#"CA certificate
    This can either be a path to the file, or a string starting with
    "-----BEGIN CERTIFICATE-----""#))]
    pub ca_cert: String,

    #[patch(attribute(clap(long)))]
    #[patch(attribute(doc = "Outside (wire) MTU"))]
    pub outside_mtu: usize,

    #[patch(attribute(clap(short, long)))]
    #[patch(attribute(doc = "Tun device name to use"))]
    pub tun_name: Option<String>,

    #[cfg(windows)]
    #[patch(attribute(clap(long)))]
    #[patch(attribute(doc = "Path to wintun.dll file (Windows only)"))]
    pub wintun_file: Option<String>,

    #[cfg(windows)]
    #[patch(attribute(clap(long)))]
    #[patch(attribute(doc = r#"
    Fixed GUID for the Wintun adapter (Windows only).
    Ensures adapter creation retries reuse the same device node.
    Accepts a UUID string (e.g. "550e8400-e29b-41d4-a716-446655440000")."#))]
    pub device_guid: Option<String>,

    #[patch(attribute(clap(long)))]
    #[patch(attribute(doc = "Local IP to use in Tun device"))]
    pub tun_local_ip: Ipv4Addr,

    #[patch(attribute(clap(long)))]
    #[patch(attribute(doc = "Peer IP to use in Tun device"))]
    pub tun_peer_ip: Ipv4Addr,

    #[patch(attribute(clap(long)))]
    #[patch(attribute(doc = "DNS IP to use in Tun device"))]
    pub tun_dns_ip: Ipv4Addr,

    #[cfg(feature = "postquantum")]
    #[patch(attribute(clap(long, value_enum)))]
    pub keyshare: KeyShare,

    #[patch(attribute(clap(long)))]
    #[patch(attribute(doc = "Interval between keepalives"))]
    #[schemars(schema_with = "lightway_app_utils::args::nonzero_duration_schema")]
    pub keepalive_interval: NonZeroDuration,

    #[patch(attribute(clap(long)))]
    #[patch(attribute(doc = "Keepalive timeout"))]
    #[schemars(schema_with = "lightway_app_utils::args::nonzero_duration_schema")]
    pub keepalive_timeout: NonZeroDuration,

    #[patch(attribute(clap(long)))]
    #[patch(empty_value = false)]
    #[patch(attribute(serde(default)))]
    #[patch(attribute(doc = "Enable continuous Keepalive"))]
    pub keepalive_continuous: bool,

    #[patch(attribute(clap(long)))]
    #[patch(attribute(doc = r#"Time it takes to trigger a tracer packet
    when we haven't received an outside packet"#))]
    #[schemars(schema_with = "lightway_app_utils::args::nonzero_duration_schema")]
    pub tracer_packet_timeout: NonZeroDuration,

    // NOTE: also "Defer timeout" in mobile device
    #[patch(attribute(clap(long)))]
    #[patch(
        attribute(doc = r#"How long to wait before selecting the best connection.
    If the preferred connection connects before the timeout, it will be used immediately."#)
    )]
    #[schemars(schema_with = "lightway_app_utils::args::duration_schema")]
    pub preferred_connection_wait_interval: Duration,

    #[patch(attribute(clap(long)))]
    #[patch(attribute(doc = "Socket send buffer size"))]
    #[schemars(schema_with = "byte_size_schema")]
    pub sndbuf: ByteSize,

    #[patch(attribute(clap(long)))]
    #[patch(attribute(doc = "Socket receive buffer size"))]
    #[schemars(schema_with = "byte_size_schema")]
    pub rcvbuf: ByteSize,

    #[cfg(batch_receive)]
    #[patch(attribute(clap(long)))]
    #[patch(empty_value = false)]
    #[patch(attribute(serde(default)))]
    #[patch(attribute(
        doc = "Enable batch receive (`recvmsg_x` on macOS, `recvmmsg` on Linux/Android))"
    ))]
    pub enable_batch_receive: bool,

    #[cfg(desktop)]
    #[patch(attribute(clap(long, value_enum)))]
    #[patch(attribute(doc = r#"Setup of route table
    Modes:
        default: Sets up routes as specified in server, tun_local_ip, tun_peer_ip, tun_dns_ip
        noexec : Does not setup any routes
        lan    : Sets up default + additional lan routes"#))]
    pub route_mode: RouteMode,

    #[cfg(desktop)]
    #[patch(attribute(clap(long, value_enum)))]
    #[patch(attribute(doc = r#"DNS configuration mode
    Modes:
        default: Sets up DNS Configuration based on target platform
        noexec : Skips DNS Configuration setup"#))]
    pub dns_config_mode: DnsConfigMode,

    #[patch(attribute(clap(long, value_enum)))]
    #[patch(attribute(doc = "Log level to use"))]
    pub log_level: LogLevel,

    #[patch(attribute(clap(long)))]
    #[patch(empty_value = false)]
    #[patch(attribute(serde(default)))]
    #[patch(attribute(doc = "Enable Expresslane for [`ConnectionType::Udp`] connections"))]
    pub enable_expresslane: bool,

    #[patch(attribute(clap(long)))]
    #[patch(empty_value = false)]
    #[patch(attribute(serde(default)))]
    #[patch(attribute(doc = "Enable PMTU discovery for [`ConnectionType::Udp`] connections"))]
    pub enable_pmtud: bool,

    #[patch(attribute(clap(long)))]
    #[patch(attribute(doc = "Base MTU to use for PMTU discovery"))]
    pub pmtud_base_mtu: Option<u16>,

    #[patch(attribute(clap(long)))]
    #[patch(empty_value = false)]
    #[patch(attribute(serde(default)))]
    #[patch(attribute(doc = "Enable IO-uring interface for Tunnel"))]
    pub enable_tun_iouring: bool,

    // Any value more than 1024 negatively impact the throughput
    #[patch(attribute(clap(long)))]
    #[patch(attribute(doc = r#"IO-uring submission queue count.
    Only applicable when `enable_tun_iouring` is `true`"#))]
    pub iouring_entry_count: usize,

    #[patch(attribute(clap(long)))]
    #[patch(attribute(doc = r#"IO-uring sqpoll idle time.
    If non-zero use a kernel thread to perform submission queue polling.
    After the given idle time the thread will go to sleep."#))]
    #[schemars(schema_with = "lightway_app_utils::args::duration_schema")]
    pub iouring_sqpoll_idle_time: Duration,

    #[patch(attribute(clap(short, long)))]
    #[patch(empty_value = false)]
    #[patch(attribute(serde(default)))]
    #[patch(
        attribute(doc = r#"Enable inside packet encoding once lightway connects
    Only used if a codec is set"#)
    )]
    pub enable_inside_pkt_encoding_at_connect: bool,

    #[cfg(feature = "debug")]
    #[patch(attribute(clap(long)))]
    #[patch(attribute(doc = "File path to save wireshark keylog"))]
    pub keylog: Option<PathBuf>,

    #[cfg(feature = "debug")]
    #[patch(attribute(clap(long)))]
    #[patch(empty_value = false)]
    #[patch(attribute(serde(default)))]
    #[patch(attribute(doc = "Enable WolfSSL debug logging"))]
    pub tls_debug: bool,

    #[cfg(windows)]
    #[patch(attribute(clap(long)))]
    #[patch(
        attribute(doc = r#"Wintun ring buffer capacity in bytes (Windows only).
    Must be a power of two between 128KiB and 64MiB.
    Larger values improve throughput."#)
    )]
    #[schemars(schema_with = "byte_size_schema")]
    pub wintun_ring_capacity: ByteSize,

    #[cfg(windows)]
    #[patch(attribute(clap(long)))]
    #[patch(empty_value = false)]
    #[patch(attribute(serde(default)))]
    #[patch(attribute(doc = r#"Enable DPAPI encryption/decryption for config file
    Only for Windows platform"#))]
    pub enable_dpapi: bool,

    /// SNI header for TLS connections
    #[cfg(feature = "mobile")]
    #[patch(attribute(clap(skip)))]
    pub sni_header: String,
}

impl Config {
    /// Try build auth from config
    pub fn take_auth(&mut self) -> Result<AuthMethod, Error> {
        take_auth(self.token.take(), self.user.take(), self.password.take())
    }

    /// Try build CA from ca_crt
    pub fn load_ca(&self) -> Result<lightway_core::wolfssl::RootCertificate<'_>, Error> {
        load_ca(&self.ca_cert)
    }

    /// Try build CA from ca_crt file
    /// If input ca_path is none, will take ca_cert field as path and pass to SSL
    pub fn load_ca_file<'a>(
        &self,
        ca_path: &'a mut Option<PathBuf>,
    ) -> lightway_core::wolfssl::RootCertificate<'a> {
        if ca_path.is_none() {
            *ca_path = Some(PathBuf::from(&self.ca_cert));
        }
        RootCertificate::PemFileOrDirectory(
            ca_path
                .as_ref()
                .expect("the path already initialized if it is none"),
        )
    }

    #[cfg(feature = "mobile")]
    pub fn apply_mobile_config(&mut self, config: MobileConfig) {
        match config.dns_ip.parse::<Ipv4Addr>() {
            Ok(ip) => self.tun_dns_ip = ip,
            Err(e) => tracing::warn!("dns ip is invalid: {e}. Using default."),
        }

        match config.local_ip.parse::<Ipv4Addr>() {
            Ok(ip) => self.tun_local_ip = ip,
            Err(e) => tracing::warn!("local ip is invalid: {e}. Using default."),
        }

        if let Ok(defer_interval) = u64::try_from(config.defer_timeout) {
            self.preferred_connection_wait_interval =
                Duration::from_std_duration(StdDuration::from_millis(defer_interval));
        } else {
            tracing::warn!(
                "Defer timeout value {} is invalid. Using default value.",
                config.defer_timeout
            );
        }

        let MobileConfig {
            enable_heart_beat,
            enable_expresslane,
            sni_header,
            ..
        } = config;

        self.keepalive_continuous = enable_heart_beat;
        self.enable_expresslane = enable_expresslane;
        self.sni_header = sni_header
    }

    #[cfg(feature = "mobile")]
    pub fn apply_mobile_connect_configs(&mut self, configs: Vec<MobileConnectionConfig>) {
        self.servers = configs.into_iter().map(|c| c.into()).collect()
    }
}

impl Default for Config {
    fn default() -> Config {
        Config {
            config_file: PathBuf::default(),
            generate: ConfigFormat::Yaml,
            servers: Vec::default(),
            server: String::default(),
            mode: ConnectionType::Tcp,
            server_dn: None,
            cipher: Cipher::Aes256,
            token: None,
            user: None,
            password: None,
            ca_cert: "./ca_cert.crt".to_string(),
            outside_mtu: MAX_OUTSIDE_MTU,
            #[cfg(macos)]
            tun_name: None,
            #[cfg(not(macos))]
            tun_name: Some("lightway".to_string()),
            #[cfg(windows)]
            wintun_file: None,
            #[cfg(windows)]
            device_guid: None,
            tun_local_ip: Ipv4Addr::new(100, 64, 0, 6),
            tun_peer_ip: Ipv4Addr::new(100, 64, 0, 5),
            tun_dns_ip: Ipv4Addr::new(100, 64, 0, 1),
            #[cfg(feature = "postquantum")]
            keyshare: KeyShare::default(),
            keepalive_interval: NonZeroDuration::from_std_duration(StdDuration::from_secs(10)),
            keepalive_timeout: NonZeroDuration::from_std_duration(StdDuration::from_secs(60)),
            keepalive_continuous: true,
            tracer_packet_timeout: NonZeroDuration::from_std_duration(StdDuration::from_secs(10)),
            preferred_connection_wait_interval: Duration::from_std_duration(
                StdDuration::from_secs(0),
            ),
            sndbuf: ByteSize::mib(8),
            rcvbuf: ByteSize::mib(8),
            #[cfg(batch_receive)]
            enable_batch_receive: false,
            #[cfg(desktop)]
            route_mode: RouteMode::default(),
            #[cfg(desktop)]
            dns_config_mode: DnsConfigMode::default(),
            log_level: LogLevel::Info,
            enable_expresslane: false,
            enable_pmtud: false,
            pmtud_base_mtu: None,
            enable_tun_iouring: false,
            iouring_entry_count: 1024,
            iouring_sqpoll_idle_time: Duration::from_std_duration(StdDuration::from_millis(100)),
            enable_inside_pkt_encoding_at_connect: false,
            #[cfg(feature = "debug")]
            keylog: None,
            #[cfg(feature = "debug")]
            tls_debug: false,
            #[cfg(windows)]
            wintun_ring_capacity: ByteSize::mib(8),
            #[cfg(windows)]
            enable_dpapi: false,
            #[cfg(feature = "mobile")]
            sni_header: String::new(),
        }
    }
}

#[serde_inline_default::serde_inline_default]
#[derive(Clone, Default, Parser, Debug, Deserialize, JsonSchema, Serialize, PartialEq)]
pub struct ConnectionConfig {
    /// Server to connect to in `<hostname>:<port>` format
    pub server: String,

    /// Connection mode
    #[serde(default)]
    pub mode: ConnectionType,

    /// Server domain name
    #[serde(default)]
    pub server_dn: Option<String>,

    /// Cipher to use for encryption
    #[serde(default)]
    pub cipher: Cipher,

    /// Username for User/Pass Auth
    #[serde(default)]
    pub username: Option<String>,

    /// Passwordfor User/Pass Auth
    #[serde(default)]
    pub password: Option<String>,

    /// Auth token
    #[serde(default)]
    pub token: Option<String>,

    /// Outside mtu
    #[serde_inline_default(MAX_OUTSIDE_MTU)]
    pub outside_mtu: usize,

    /// The CA Cert content or Path
    #[serde(default)]
    pub ca_cert: Option<String>,
}

impl ConnectionConfig {
    /// Try build auth from config
    #[cfg(feature = "mobile")]
    pub fn take_auth(&mut self) -> Result<AuthMethod, Error> {
        take_auth(
            self.token.take(),
            self.username.take(),
            self.password.take(),
        )
    }

    /// Try build CA from ca_crt
    #[cfg(feature = "mobile")]
    pub fn load_ca(&self) -> Result<lightway_core::wolfssl::RootCertificate<'_>, Error> {
        self.ca_cert
            .as_ref()
            .map(|ca| load_ca(ca))
            .ok_or(Error::InvalidCertificate)?
    }

    /// Try build SocketAddress from server field
    #[cfg(feature = "mobile")]
    pub fn skt_addr(&self) -> Result<std::net::SocketAddr, Error> {
        Ok(self
            .server
            .parse()
            .map_err(|_e| Error::InvalidSocketAddress)?)
    }
}

#[derive(Debug, thiserror::Error)]
#[cfg_attr(
    all(feature = "mobile", not(feature = "mobile-test")),
    derive(uniffi::Error)
)]
pub enum Error {
    /// Invalid network protocol
    #[error("Invalid network protocol")]
    #[allow(dead_code)]
    InvalidProtocol,

    /// Unable to load certificate
    #[error("Unable to load certificate")]
    InvalidCertificate,

    #[cfg(feature = "mobile")]
    /// Unable to parse the sokcet address
    #[error("Invalid Socket Address")]
    InvalidSocketAddress,

    /// Lack information to Authentication
    #[error("Insufficient information for Authentication")]
    InsufficientAuth,
}

#[cfg(any(feature = "mobile", feature = "mobile-test"))]
#[derive(Debug)]
#[cfg_attr(
    all(feature = "mobile", not(feature = "mobile-test")),
    derive(uniffi::Record)
)]
/// User settings from the mobile app, it is a small set config and easier to use in mobile
pub struct MobileConfig {
    /// Enable continuous/NAT keep-alive
    pub enable_heart_beat: bool,
    /// SNI header for TLS connections
    pub sni_header: String,
    /// Defer timeout in milliseconds
    defer_timeout: i64,
    /// Enable Expresslane for UDP connections
    pub enable_expresslane: bool,
    /// The local ip for TUN interface in ipv4 format
    pub local_ip: String,
    /// The dns ip in ipv4 format
    pub dns_ip: String,
}

/// Endpoint settings from the mobile app, it is a small set and easier to use in mobile
#[cfg(feature = "mobile")]
#[derive(Clone)]
#[cfg_attr(
    all(feature = "mobile", not(feature = "mobile-test")),
    derive(uniffi::Record)
)]
pub struct MobileConnectionConfig {
    pub server_ip: IpAddress,
    pub port: u16,
    pub server_dn: String,
    pub username: Option<String>,
    pub password: Option<String>,
    pub auth_token: Option<String>,
    pub ca_cert: String,
    pub use_tcp: bool,
    pub use_cha_cha_20: bool,
    pub outside_mtu: u32,
}

#[cfg(feature = "mobile")]
impl From<MobileConnectionConfig> for ConnectionConfig {
    fn from(
        MobileConnectionConfig {
            server_ip,
            port,
            server_dn,
            username,
            password,
            auth_token,
            ca_cert,
            use_tcp,
            use_cha_cha_20,
            outside_mtu,
        }: MobileConnectionConfig,
    ) -> ConnectionConfig {
        ConnectionConfig {
            server: format!("{}:{}", server_ip.ip.to_string(), port),
            mode: if use_tcp {
                ConnectionType::Tcp
            } else {
                ConnectionType::Udp
            },
            server_dn: if server_dn.trim().is_empty() {
                None
            } else {
                Some(server_dn)
            },
            cipher: if use_cha_cha_20 {
                Cipher::Chacha20
            } else {
                Cipher::default()
            },
            username,
            password,
            token: auth_token,
            outside_mtu: outside_mtu as usize,
            ca_cert: if ca_cert.trim().is_empty() {
                None
            } else {
                Some(ca_cert)
            },
        }
    }
}

// Ref: https://mozilla.github.io/uniffi-rs/0.27/proc_macro/index.html#the-unifficustom_type-and-unifficustom_newtype-macros
#[cfg(all(feature = "mobile", not(feature = "mobile-test")))]
uniffi::custom_type!(IpAddress, String);

#[cfg(feature = "mobile")]
#[derive(Debug, Eq, PartialEq, Clone)]
/// Custom type  with `String` as the `Builtin` bridge
pub struct IpAddress {
    pub ip: IpAddr,
}

#[cfg(feature = "mobile")]
impl std::fmt::Display for IpAddress {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.ip)
    }
}

#[cfg(all(feature = "mobile", not(feature = "mobile-test")))]
impl crate::UniffiCustomTypeConverter for IpAddress {
    type Builtin = String;

    fn into_custom(val: Self::Builtin) -> uniffi::Result<Self> {
        use std::str::FromStr;
        Ok(IpAddress {
            ip: IpAddr::from_str(val.as_str())?,
        })
    }

    fn from_custom(obj: Self) -> Self::Builtin {
        obj.ip.to_string()
    }
}

#[cfg(feature = "mobile")]
impl From<IpAddress> for IpAddr {
    fn from(val: IpAddress) -> Self {
        val.ip
    }
}

fn take_auth(
    token: Option<String>,
    user: Option<String>,
    password: Option<String>,
) -> Result<AuthMethod, Error> {
    match (token, user, password) {
        (Some(token), _, _) => Ok(AuthMethod::Token { token }),
        (_, Some(user), Some(password)) => Ok(AuthMethod::UserPass { user, password }),
        _ => Err(Error::InsufficientAuth),
    }
}

fn load_ca(ca: &String) -> Result<lightway_core::wolfssl::RootCertificate<'_>, Error> {
    if ca.starts_with("-----BEGIN CERTIFICATE-----") {
        Ok(RootCertificate::PemBuffer(ca.as_bytes()))
    } else {
        Err(Error::InvalidCertificate)
    }
}

fn byte_size_schema(generator: &mut schemars::SchemaGenerator) -> schemars::Schema {
    let mut schema = String::json_schema(generator);
    schema.insert(
        "pattern".into(),
        "^[0-9]+(\\.[0-9]+)?\\s*(EB|EIB|GB|GIB|KB|KIB|MB|MIB|PB|PIB|TB|TIB|eb|eib|gb|gib|kb|kib|mb|mib|pb|pib|tb|tib)$".into(),
    );
    schema
}

#[cfg(test)]
mod tests {
    use std::fs::read_to_string;
    use std::str::FromStr;

    use super::*;
    use regex::Regex;
    use schemars::SchemaGenerator;
    use test_case::test_case;

    #[test_case("../tests/client/client_config.yaml", true, 0)]
    #[test_case(
        "../tests/client/parallel_connect/client_config.tcp_then_udp.yaml",
        false,
        2
    )]
    #[test_case("../tests/client/parallel_connect/client_config.tcp.yaml", false, 10)]
    #[test_case(
        "../tests/client/parallel_connect/client_config.udp_then_tcp.yaml",
        false,
        2
    )]
    #[test_case("../tests/client/parallel_connect/client_config.udp.yaml", false, 10)]
    fn test_parse_config(config_file: &str, has_top_level_server: bool, servers_len: usize) {
        let matches =
            ConfigPatch::try_parse_from(["lightway-client", "--config-file", config_file]);
        let mut config = Config::default();
        let config_file = PathBuf::from_str(config_file).unwrap();
        let yaml_patch =
            serde_saphyr::from_str::<ConfigPatch>(&read_to_string(config_file).unwrap()).unwrap();
        config.apply(yaml_patch);
        config.apply(matches.unwrap());

        assert_eq!(config.server.is_empty(), !has_top_level_server);
        assert_eq!(config.servers.len(), servers_len);
    }

    fn get_byte_pattern() -> String {
        let schema = byte_size_schema(&mut SchemaGenerator::default());
        schema
            .get("pattern")
            .and_then(|v| v.as_str())
            .expect("pattern key must exist and be a string")
            .to_string()
    }

    #[test]
    fn valid_byte_size_input() {
        let re = Regex::new(&get_byte_pattern()).unwrap();
        for s in &["1KB", "1MB", "1GB", "1TB", "1PB", "1EB"] {
            assert!(
                re.is_match(s),
                "expected valid with si units uppercase input: {s}"
            );
        }
        for s in &["1KIB", "1MIB", "1GIB", "1TIB", "1PIB", "1EIB"] {
            assert!(
                re.is_match(s),
                "expected valid with iec units uppercase input: {s}"
            );
        }
        for s in &["1kb", "1mb", "1gb", "1tb", "1pb", "1eb"] {
            assert!(
                re.is_match(s),
                "expected valid with si units lowercase input: {s}"
            );
        }
        for s in &["1kib", "1mib", "1gib", "1tib", "1pib", "1eib"] {
            assert!(
                re.is_match(s),
                "expected valid with iec units lowercase input: {s}"
            );
        }
        for s in &["1.5KB", "0.5mb", "2.25GIB", "10.0tb"] {
            assert!(re.is_match(s), "expected valid with decimal input: {s}");
        }
        for s in &["1 KB", "10  MB", "1.5\tGIB", "100 tb"] {
            assert!(
                re.is_match(s),
                "expected valid with whitespace spacer input: {s}"
            );
        }
        for s in &["512MB", "1024KIB", "8gb"] {
            assert!(re.is_match(s), "expected valid with no spacer input: {s}");
        }
        for s in &["999999GB", "123456789TB", "1000000EIB"] {
            assert!(
                re.is_match(s),
                "expected valid with larger number input: {s}"
            );
        }
    }

    #[test]
    fn invalid_byte_size_input() {
        let re = Regex::new(&get_byte_pattern()).unwrap();
        assert!(!re.is_match(""), "empty string must not match");
        assert!(!re.is_match("1024"), "bare number must not match");
        for s in &["KB", "MIB", "gb"] {
            assert!(!re.is_match(s), "unit without number must not match: {s}");
        }
        for s in &["1B", "1YB", "1ZB", "1bit", "1byte", "1kbps"] {
            assert!(!re.is_match(s), "unknown unit must not match: {s}");
        }
        for s in &["1Kb", "1mB", "1Gib", "1tIb"] {
            assert!(!re.is_match(s), "mixed case must not match: {s}");
        }
        assert!(!re.is_match(".5KB"), "leading dot must not match");
        assert!(!re.is_match("1.2.3KB"), "multiple dots must not match");
        assert!(!re.is_match("-1KB"), "negative value must not match");
        for s in &["1KBs", "1MB/s", "1GIB "] {
            assert!(!re.is_match(s), "trailing content must not match: {s}");
        }
        for s in &["~1KB", "about 1MB", " 1GB"] {
            assert!(!re.is_match(s), "leading text must not match: {s}");
        }
        for s in &["1GB 512MB", "1TB1GB"] {
            assert!(
                !re.is_match(s),
                "multi-component byte size must not match: {s}"
            );
        }
    }
}
