[package]
name = "lightway-core"
version = "0.1.0"
repository.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
debug = ["wolfssl/debug"]
# Enable additional APIs to support wire protocol fuzzing
fuzzing_api = []
postquantum = ["wolfssl/postquantum"]
kyber_only = ["wolfssl/kyber_only"]

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
bytes.workspace = true
delegate.workspace = true
if_chain = "1.0.2"
lru = "0.12.1"
metrics.workspace = true
more-asserts.workspace = true
num_enum = "0.7.0"
once_cell = "1.19.0"
pnet.workspace = true
rand.workspace = true
rand_core = "0.6.4"
thiserror.workspace = true
tracing.workspace = true
wolfssl = { git = "https://github.com/expressvpn/wolfssl-rs", default-features = false}

[dev-dependencies]
async-trait.workspace = true
itertools = "0.14.0"
lightway-app-utils.workspace = true
test-case.workspace = true
tokio.workspace = true
tokio-stream.workspace = true
