[package]
name = "lightway-core"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/expressvpn/lightway"
authors = ["lightway-developers@expressvpn.com"]
license = "GPL-2.0"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
debug = ["wolfssl/debug"]
# Enable additional APIs to support wire protocol fuzzing
fuzzing_api = []
postquantum = ["wolfssl/postquantum"]

[dependencies]
bytes = "1.4.0"
num_enum = "0.7.0"
thiserror = "1.0.47"
more-asserts = "0.3.1"
wolfssl = { git = "https://github.com/expressvpn/wolfssl-rs", default-features = false }
rand = "0.8.5"
rand_core = "0.6.4"
tracing = "0.1.37"
pnet = "0.34.0"
delegate = "0.12.0"
lru = "0.12.1"
once_cell = "1.19.0"
metrics = "0.23.0"
if_chain = "1.0.2"

[dev-dependencies]
async-trait = "0.1.73"
test-case = "3.1.0"
itertools = "0.13.0"
tokio = { version = "1.31.0", features = ["rt-multi-thread", "macros", "net", "time", "sync", "io-util"] }
tokio-stream = { version = "0.1.14" }
lightway-app-utils = { path = "../lightway-app-utils" }
