name: Nix build / macos

on:
  workflow_call:

jobs:
  flake-check:
    timeout-minutes: 30
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: ./.github/actions/nix-setup
      - run: nix flake check

  build:
    timeout-minutes: 90
    name: ${{ matrix.package }}
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - package: lightway-aarch64-darwin
            verify_type: "skip"
            build_type: "native"
          - package: lightway-aarch64-darwin-msrv
            verify_type: "skip"
            build_type: "native"

    steps:
      - uses: actions/checkout@v7.0.1

      - uses: ./.github/actions/nix-setup
      - uses: ./.github/actions/nix-build
        with:
          package: ${{ matrix.package }}
          platform: aarch64-darwin
          build_type: ${{ matrix.build_type }}
          verify_type: ${{ matrix.verify_type }}
